import './globals.css'
import {Navbar, ParticlesCanvas, Sidebar} from "@/components";
import React from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={""}>
      <ParticlesCanvas/>
      <Navbar/>
      <Sidebar/>
      {children}
      </body>
    </html>
  )
}
